---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ service.namespace }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ build.name }}
  namespace: {{ service.namespace }}
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9090
      targetPort: web
  selector:
    prometheus: {{ build.name }}

---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: {{ build.name }}
  namespace: {{ service.namespace }}
spec:
  serviceAccountName: {{ build.name }}
  serviceMonitorSelector:
    matchLabels:
      ambassador: monitoring
  resources:
    requests:
  memory: 400Mi

# ----------------------------------------------------------------------------------------------------------------------
# Prometheus RBAC
# ----------------------------------------------------------------------------------------------------------------------
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: {{ service.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ build.name }}
  namespace: {{ service.namespace }}
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ build.name }}
  namespace: {{ service.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ build.name }}
subjects:
  - kind: ServiceAccount
    name: {{ build.name }}
    namespace: {{ service.namespace }}
