---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ service.namespace }}

# ----------------------------------------------------------------------------------------------------------------------
# Prometheus Operator RBAC
# ----------------------------------------------------------------------------------------------------------------------
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ build.name }}
  namespace: {{ service.namespace }}
rules:
  - apiGroups:
      - extensions
    resources:
      - thirdpartyresources
    verbs:
      - "*"
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - alertmanagers
      - prometheuses
      - servicemonitors
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs: ["*"]
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
    verbs: ["*"]
  - apiGroups: [""]
    resources:
      - pods
    verbs: ["list", "delete"]
  - apiGroups: [""]
    resources:
      - services
      - endpoints
    verbs: ["get", "create", "update"]
  - apiGroups: [""]
    resources:
      - nodes
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources:
      - namespaces
    verbs: ["list"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ build.name }}
  namespace: {{ service.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ build.name }}
subjects:
  - kind: ServiceAccount
    name: {{ build.name }}
    namespace: {{ service.namespace }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ build.name }}
  namespace: {{ service.namespace }}

# ----------------------------------------------------------------------------------------------------------------------
# Prometheus Operator
# ----------------------------------------------------------------------------------------------------------------------
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ build.name }}
  namespace: {{ service.namespace }}
  labels:
    k8s-app: {{ build.name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: {{ build.name }}
    spec:
      containers:
      - args:
          - --kubelet-service=kube-system/kubelet
          - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        image: quay.io/coreos/prometheus-operator:v0.15.0
        name: prometheus-operator
        ports:
          - containerPort: 8080
            name: http
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      serviceAccountName: {{ build.name }}
