---
name: prometheus-operator
namespace: monitoring-system

profiles:
  dev:
    name: {{ branch.replace('/', '-') }}
  staging:
    name: next
  stable: { }

branches:
  master: stable
  dev/*:  dev
