---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ service.namespace }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ build.name }}
  namespace: {{ service.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    name: {{ build.name }}
    component: core

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ build.name }}-core
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ build.name }}
        component: core
    spec:
      containers:
      - image: {{ service.grafana_image }}
        name: grafana-core
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
          # The following env variables set up basic auth with the default admin user and admin password.
          - name: GF_AUTH_BASIC_ENABLED
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "false"
        readinessProbe:
          httpGet:
            path: /login
            port: 3000
        volumeMounts:
        - name: grafana-persistent-storage
          mountPath: /var
      volumes:
      - name: grafana-persistent-storage
        emptyDir: {}
